### ISSUE TITLE
[2.0] Todo

### ISSUE THREAD

**Issue by mikerockett** [rockettpw/jumplinks#14]
Placing this here for convenience and easy of access.
Complete todo list for version 2.0, in no particular order:

**Features**
- [x] Proper subdomain support (tested thoroughly with symbolicd links)
- [x] Basic jumplinks
- [x] Parameter-based jumplinks
  - [x] Parameter aliasing: `{alias}`
  - [x] Parameter type hinting `{param:type}`
  - [x] Default FastRoute syntax `{param:regex}`
- [ ] Support for optional parts (partial support from FastRoute so far)
- [x] Time filtering (start and end) (backend implementation complete)
- [x] Collections (backend implementation complete) (new format: `{collection[key]|optional,flags}`)
  - [x] Standard collections
  - [x] Collection parameter flags (`raw`, `dontskip`)
- [ ] Unicode URI support (#13) (might already be supported, not yet tested)
- [ ] Exporter (CSV, JSON) (#12)
- [ ] Importer (CSV, JSON, ProcessRedirects [maybe])
- [ ] Multi-language (awaiting feedback from [forum post](https://processwire.com/talk/topic/8697-jumplinks/?do=findComment&comment=125461))
- [ ] Hit logging (plus [resets](https://processwire.com/talk/topic/8697-jumplinks/?do=findComment&comment=123415))
- [ ] Re-ordering
- [ ] State toggling (point 1 of [this post](https://processwire.com/talk/topic/8697-jumplinks/?do=findComment&comment=123408) and [response](https://processwire.com/talk/topic/8697-jumplinks/?do=findComment&comment=123410))
- [ ] Link testing (point 1 of [this post](https://processwire.com/talk/topic/8697-jumplinks/?do=findComment&comment=112006))
- [ ] Stale jumplink indicator
- [ ] Temporary module deactivation ([this post](https://processwire.com/talk/topic/8697-jumplinks/?do=findComment&comment=112487))

**Module Development**
- [x] Module structure
  - [x] Composer
  - [x] PSR-4 for Jumplinks namespace
  - [x] illuminate/database 5.0
  - [x] nesbot/carbon
  - [x] nikic/fast-route
- [x] FastRoute dispatch mapping
- [x] Eloquent models (`Jumplink`, `Collection`) with accessors and conversion/compilation methods
- [x] Traits (various, for SoC)
- [x] Utilities (`Helpers`, `UserAgent`, `RegExDefinitions`)
- [x] Testing phase 1 (basic `testHandler`)
- [ ] Frontend components (this may take a while)
- [ ] Migration handler (1.5.x to 2.0)
- [x] Debug logging (mostly complete)
- [ ] Module config

**Documentation**
- [ ] Split docs repo into branches for 1.5 and 2.0
- [ ] Recode doc site to incorporate branches
- [ ] Compile 2.0 docs

**Comment by mikerockett** [comment]
### Benchmarking

Benchmarks will be performed on 250, 500, and 1000 jumplinks. The latter two are not really necessary as the wise use of the module (best combination of dynamic jumplinks, collections, and selectors) will increase performance on large installations. As a side note, FastRoute has already shown a performance increase, but all of this still needs to be benchmarked.

**Update 2016/09/28:** Prelim-benchmarks show that the page loading speed has increased two-fold due to the use of DataTables. This is mostly apparent on large data-sets (6000 jumplinks tested), of course. All-in-all, however, v2 feels a lot snappier at present. Also, the use of FastRoute has made redirects much quicker, especially on large datasets.

**Comment by mikerockett** [comment]
### Composer and PW version requirement

The original intention was to make the module compatible with both PW 2.8-legacy and 3.0. However, as Benjamin Milde [points out](https://processwire.com/talk/topic/14400-pw-3035-processwire-3-master-and-changelog/#comment-129442), the 2.8 legacy is not meant for new sites, but rather for old ones wanting new features that PW3 has, without the need for namespaces.

As a result, and due to the namespacing conflicts/other-related-issues, Jumplinks 2 will now only be for PW3. Additionally, and as noted in the roadmap above, the project dependencies will need to be declared and installed before the module has been installed. Unfortunately, this means that Jumplinks to will only be installed by means of a call to `composer require rockettpw/jumplinks`. Additionally, I would assume that the only full-proof way to update it would be through the relevant composer call to `update`.

Checking for upgrades in the PW admin interface would work, but any updated dependencies would not be pulled automatically, and so the `update` call would need to be made anyway.

I've gone ahead and created a Packagist account for `rockettpw`.

**Comment by mikerockett** [comment]
### 404 Monitor

The 404 monitor will not be implemented in Jumplinks 2.

As discussed on the forum thread, this will be moved into a separate module that integrates with Jumplinks if it is installed. The monitor will more than likely not be released alongside the first alpha of JL2, but my plan is to release stable versions of both modules at the same time.

**Comment by tbba** [comment]
Does this mean that the module cannot used any more as normal PW module without composer (which we do not run due to policy)? That is bad news for me. I was worried already that the project could get overcomplicated and ends as a special interest item. What a pitty that V1 is not language aware so I could simply stick with that one.

**Comment by mikerockett** [comment]
@tbba - I see, wasn't aware of anyone not beig able to use Composer due to policy. What is the purpose of this policy, if I may ask?

**Comment by mikerockett** [comment]
> I was worried already that the project could get overcomplicated

The aim is not to overcomplicate the module at all. Could you elaborate what you mean by that?

**Comment by tbba** [comment]
Hi Mike, no offense here. It's your module, your spare time and you can make it anyway you want. That is perfectly fine with me. :-)
It is only that we do not deliver PW with modules which cannot be installed/uninstalled/updated the normal way that ProcessWire indicates. (For discussing policies this is maybe not the right place?) Since you have this roadmap, which is helpful, this gives me time ahead early to start thinking about alternatives for us. I just wanted to be sure I understood this correctly.

**Comment by mikerockett** [comment]
@tbba - I see. In that case, I do envisage PW better embracing Composer in the future to reduce the install-steps back down to the one we know and love. (Refer: [Comment 129486](https://processwire.com/talk/topic/14400-pw-3035-processwire-3-master-and-changelog/#comment-129486))

At this point, it can be quite confusing. I really want the vendor directory to be included in the module package, but that means that the file compiler gets its hands on it and causes unintended side effects. If I can find a way to get rid of these effects, then I can proceed as-is until such time as PW is more Composer-integrated (or vice-versa, whichever one it is/will be).

**Comment by mikerockett** [comment]
Ah! Found the exclusions array!

```php
$config->fileCompilerOptions('exclusions', [
    str_replace('\\', '/', __DIR__ . '/modules/ProcessJumplinks/vendor/illuminate/support/helpers.php'),
]);
```

😀

**Comment by mikerockett** [comment]
So my next step is to see what can be done about setting this outside of the config.php file (an extra, unnecessary step).

**Comment by mikerockett** [comment]
I've opened https://github.com/processwire/processwire-requests/issues/18 and [sent along a PR](https://github.com/processwire/processwire/issues/13). If this is merged, then we're back to the normal install method.

**Comment by tbba** [comment]
That would be brilliant.

**Comment by mikerockett** [comment]
With regards to this issue about the vendor directory, it appears that the best method is to install via Composer instead of the admin panel. Not sure how to prevent installation via the admin panel other than providing the new method.

I feel quite bad as I keep swaying from one end of the stick to the other, but I would still like to lean towards leaving the vendor directory in the module directory as it's simply easier to manage in the current PW setup (until such time as Composer has *full* support).

Truthfully, this is all coming about due to one or two files that are not namespaced - PW is compiling these files and changing things that don't need to be changed. The files themselves are part of the Illuminate packages - specifically, the non-namespaced helpers.php file.

I have thought of using the comment to disable compilation for that file and one or two others causing a problem, but it turns out that the file compiler takes quite a while to sift through all of these. This is leading me to think about the dependencies themselves, and consider choosing packages that don't need so many dependencies.

### ORM

In JL1, PWs database/pdo connection is used to manipulate the database. For ease of access to code, statements are stored in an array, and schemas are stored in blueprints (templates). As this was not nearly as flexible as I needed it to be, I decided to switch to Eloquent for working with the DB and related models. This gives me the ability to use accessors and mutators, and have access to the schema builder everyone knows and loves from Laravel.

Whilst this is awesome, perhaps it is somewhat bulky. I have seen another, similar to Redbean, but a little more like Eloquent, called [spot2](https://github.com/vlucas/spot2) by [Vance Lucas](https://github.com/vlucas). I'd like to investigate the possibility of switching to this and lowering dependencies.

### Carbon

This is currently being used as it is required by Eloquent. This can be kept, however, as it is tiny, and doesn't use a ton of resources.

---

Switching ORMs seems to be the best route as the dependencies will be greatly reduced. The Illuminate dependencies on their own contain over 200 files. Symfony dependencies are a little over 150, and there are some other packages involved as well.

So I need a little time to work on this - apologies for the delays on my side, but I really want to make this as easy to use as possible for all users.

**Comment by TomasKostadinov** [comment]
@mikerockett Do you have any plans for when Jumplinks 2 is going to be released?

**Comment by mikerockett** [comment]
@TomasKostadinov I'm afraid I haven't had enough spare time to sit down and work on the module. Work tends to pile up at this time of year. If all goes well this week, then I'll be able to work on it this weekend. Hoping to release a beta end-December or early January.

**Comment by mikerockett** [comment]
Update: [This commit](/processwire/processwire/commit/bba6e3b00fb11c1b82a15e76941bc2eeedd511ab) solves the issue relating to the file compiler. This means that Jumplinks 2 will require either 2.8.x or at least 3.0.43. The module will do a version-check at install time.

**Comment by mikerockett** [comment]
I'm aiming for a February/March alpha/beta release. Stable will then follow shortly thereafter. My sincerest apologies for the delay -- I know there are some who have been anxiously waiting for v2 to be released; it's just a matter of how much time I have after work every day.

At this point, I'm about half-way through the roadmap. I've been fine-tuning the request handler (the handler that is called from the 404 hook), and adding logging and destination validation (see the updated notes on these). Next, I'll be focusing on adding legacy domain support, finalising the manager (mostly bulk management that needs to be taken care of), then the editors, and then the rest.

Here are some example debug snapshots (using 1000 jumplinks for performance-testing):

**Collections:**

```
Jumplinks Debug Information

ProcessWire 3.0.49, Jumplinks 2.0.0, PHP 7.0.4
Requested URI: GET /page.php?id=2&category=1 (at http://jumplinks.rockettpw.local/)
Current Timestamp: Sat, 28 Jan 2017 22:08:12 +0200

Checking for a match...
Request matches jumplink object: Jumplinks\BasicData\JumplinkData Object
(
    [description] => Obtain category and page names from their old IDs
    [from] => page.php?id={page:\d+}&category={category:\d+}
    [fromLog] => No changes made to [from] attribute
    [to] => {categories.category|dontskip,raw}/{page_ids.page}/
    [deep_clean] => 0
    [permanent] => 0
    [start] => No start
    [end] => No end
)

Collection 'page_ids' found; has value for '2' (page --> about-us):
> Cleaned value (no change): 'about-us' --> 'about-us' (deep=0)
> Applied to destination: {categories.category|dontskip,raw}/about-us/
Collection 'categories' found; has value for '1' (category --> company):
> Cleaning skipped due to presence of 'raw' flag.
> Applied to destination: company/about-us/

Jumplink is not time-filtered.
All looks good here! The following redirect will take place when debug mode is disabled:
> From: http://jumplinks.rockettpw.local/page.php?id=2&category=1
> To: http://jumplinks.rockettpw.local/company/about-us/
> HTTP Status Code: 302

[done in 0.059613 seconds]
```

**Basic Selectors:**

```
Jumplinks Debug Information

ProcessWire 3.0.49, Jumplinks 2.0.0, PHP 7.0.4
Requested URI: GET /Pages/About_Us.aspx (at http://jumplinks.rockettpw.local/)
Current Timestamp: Sat, 28 Jan 2017 22:09:12 +0200

Checking for a match...
Request matches jumplink object: Jumplinks\BasicData\JumplinkData Object
(
    [description] => ASPX basic page redirect
    [from] => Pages/{page}.aspx
    [fromLog] => Array
        (
            [original] => Pages/{page}.aspx
            [alias_expansion] => Pages/{page:segment}.aspx
            [regex_params] => Pages/{page:[\w-]+}.aspx
        )

    [to] => @[template=basic-page, name={page}]
    [deep_clean] => 1
    [permanent] => 0
    [start] => No start
    [end] => No end
)

Parameter 'page' found:
> Cleaned capture: About_Us --> about-us (deep=1)
> Applied to destination: @[template=basic-page, name=about-us]
Selector found: template=basic-page, name=about-us
> Selector returned an existing page viewable by the current user: /about-us/

Jumplink is not time-filtered.
All looks good here! The following redirect will take place when debug mode is disabled:
> From: http://jumplinks.rockettpw.local/Pages/About_Us.aspx
> To: http://jumplinks.rockettpw.local/about-us/
> HTTP Status Code: 302

[done in 0.058891 seconds]
```

**Aliasing with deep-cleaning:**

```
Jumplinks Debug Information

ProcessWire 3.0.49, Jumplinks 2.0.0, PHP 7.0.4
Requested URI: GET /2021/05/NASALaunchRevisted/ (at http://jumplinks.rockettpw.local/)
Current Timestamp: Sat, 28 Jan 2017 22:10:10 +0200

Checking for a match...
Request matches jumplink object: Jumplinks\BasicData\JumplinkData Object
(
    [description] => No description
    [from] => {year}/{month}/{post}/
    [fromLog] => Array
        (
            [original] => {year}/{month}/{post}/
            [alias_expansion] => {year:num}/{month:num}/{post:segment}/
            [regex_params] => {year:[\d]+}/{month:[\d]+}/{post:[\w-]+}/
        )

    [to] => blog/{post}/
    [deep_clean] => 1
    [permanent] => 0
    [start] => No start
    [end] => No end
)

Parameter 'post' found:
> Cleaned capture: NASALaunchRevisted --> nasa-launch-revisted (deep=1)
> Applied to destination: blog/nasa-launch-revisted/

Jumplink is not time-filtered.
All looks good here! The following redirect will take place when debug mode is disabled:
> From: http://jumplinks.rockettpw.local/2021/05/NASALaunchRevisted/
> To: http://jumplinks.rockettpw.local/blog/nasa-launch-revisted/
> HTTP Status Code: 302

[done in 0.056856 seconds]
```

**No match:** (smaller data-set)

```
Jumplinks Debug Information

ProcessWire 3.0.49, Jumplinks 2.0.0, PHP 7.0.4
Requested URI: GET /foo (at http://jumplinks.rockettpw.local/)
Current Timestamp: Sat, 28 Jan 2017 22:14:19 +0200

Checking for a match...
No matches, sorry. Here are the jumplinks that were searched:
- About_Us.html
- blog/post.php?id={id:\d+}&title={any}
- page.php?id={page:\d+}&category={category:\d+}
- {page}.{ext:htm}
- {year}/{month}/{post}/
- promo/{code:segment}/?
- partner/{partner}
- Pages/{page}.aspx
404 event will take over for non-debug users.

[done in 0.038432 seconds]
```

**Some screenies:**

![scrn_jumplinks rockettpw local-2017-01-22-17-42-50](https://cloud.githubusercontent.com/assets/4586280/22399559/7b6ec922-e5a7-11e6-8642-07cf6432273b.png)

![scrn_jumplinks rockettpw local-2017-01-28-22-15-43](https://cloud.githubusercontent.com/assets/4586280/22399560/80075cc4-e5a7-11e6-8217-64034c213728.png)

**Comment by mikerockett** [comment]
https://processwire.com/talk/topic/8697-jumplinks/?do=findComment&comment=143558

> I know I've been distant, but work has kept creeping up on me and I simply haven't been able to commit time to continue work on Jumplinks 2. At this stage, it's difficult to tell when I'll be able to continue, but I do hope it will be soon as I'd like to deprecate v1 as v2 is already so much better.

**Comment by mikerockett** [comment]
Small update: Time isn't freeing up as I'd hoped. However, I'd still like to allocate 30m to an hour each day to continue work on this.

I'd like to drop support for PW 2.8 (legacy), unless enough people would like it. My recommendation at this time would be to stick to v1 for the legacy branch of PW. This decision is really in light of the fact that Jumplinks is more commonly installed on new sites, which should all jump ship tp PW3 anyway. If you don't agree and would like to see v2 support for the legacy branch, then we can discuss below.

**Comment by mikerockett** [comment]
I think that the present state of Jumplinks 2 needs to be looked at on my end. I'm simply not comfortable with so many dependencies being imported, even though I'm looking for a solution that involves easy table migrations that cater specifically for different MySQL versions, as well as a simple model-architecture.

As such, I'm seriously considering dropping Illuminate/Database in favour of something else. Redbean is, perhaps, a good option.

Luckily, I'd only need to rewrite portions of the module, and not the entire thing.

**Comment by desbest** [comment]
http://sqlfiddle.com/

**Comment by mikerockett** [comment]
@desbest Thanks, though that only supports MySQL 5.6.

**Comment by mikerockett** [comment]
So I realised that my dependencies were actually because of other dev-dependencies I had pulled in. Faker was one of them that took a considerable amount of space.

Given this, and given that the module’s architecture is mostly done from an operations point of view (models, flow, etc), I’m going to stick with Illuminate.

Note, however, that I plan to drop support for PHP <= 5.6.3 (stable is currently at 5.6.32, so I don’t see an issue with that) and use [illuminate/database 5.4.36](/illuminate/database/tree/v5.4.36) instead of the current 5.0.

**Comment by mikerockett** [comment]
As indicated, I’ve moved over to illuminate/database 5.4.36.

I’ve also moved the resource builder to Laravel Mix, simply so I don’t have issues. I started with Rollup, but it’s quite a mess really, especially considering rollup is designed for libraries, and not necessarily in-app scripts.

For those who are not aware, Laravel Mix uses Webpack behind the scenes, automating as much as possible. A handy feature is cache busting, which versions output files – no more cache issues when resources are updated.

Unfortunately, Mix includes a lot of dependencies that are not needed in this project, but I don’t imagine many folks will be contributing in terms of resources, so this shouldn’t be an issue.

Resources are also using the new ES/ECMA standards, which help considerably in development. No more messy code.

And, as a cherry on top (well, not really a cherry no top, but it fixes an issue or two with themes), Jumplinks 2 will support all themes out of the box. There’s still a small issue with AdminThemeUIKit where the Inputfield has a doubled-up border, but it’s not really noticable, and so I don’t see it being a problem for anyone…

![image](https://user-images.githubusercontent.com/4586280/34326511-094e5506-e8b7-11e7-95b5-3f363036c434.png)
![image](https://user-images.githubusercontent.com/4586280/34326496-99b5294a-e8b6-11e7-8e01-31d0d99f47e5.png)
![image](https://user-images.githubusercontent.com/4586280/34326498-accd1af6-e8b6-11e7-85cc-65c2e2cb6ca3.png)

**Comment by jmartsch** [comment]
Hello Mr. Rocket, any news for the new version? Is ist ready to use / test yet?

**Comment by mikerockett** [comment]
In preparation for my continuation on this project in a few weeks, I'm going to be closing this issue and opening multiple issues for the [automated project board](/rockettpw/jumplinks/projects/2); this will assist in keeping track of progress a little better.

**Comment by mikerockett** [comment]
Tasks moved over to [the project board for Version 2](../projects/2). Closing.
